eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1110/eureka/
spring:
  profiles:
    active: dev
  cloud:
    config:
    label: master
    profile: dev
    uri: http://localhost:1111/
