# spring session
spring:
  session: stateless
  mvc: /file/**
  resource: 
    static-location: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./file
  
#ribbon
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
  # 失败重试 false只对get重试
  OkToRetryOnAllOperations: false

#management
management:
  endpoints:
    web:
      expose:
        include: "*"
#        exclude: env,beans
#        include: health,info,refresh

# log4j2
#logging:
  #config: ${spring.cloud.config.uri}/fast-logging-${spring.profiles.active}.yml
