# ===================================================================
# framework specific properties
# ===================================================================

# datasource
druid:
  url: jdbc:mysql://localhost:3306/cloud-vue?useUnicode=true&characterEncoding=utf8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: root
  druid.initial-size=1
druid.min-idle=1
druid.max-active=20
druid.test-on-borrow=true
