server:
  port: 1112
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fast-product
        uri: lb://fast-product
        predicates:
        - Path=/fast-product/**
        filters:
        - StripPrefix=1
        - Auth
        #- RewritePath=/employee/(?<path>.*), /$\{path}
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
