
# ===================================================================
# framework specific properties
# ===================================================================

# datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://47.112.36.171:3306/hkb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zengchao
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      pool-name: FastHiariPool
      maxium-pool-size: 12
      miniumum: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      login-timeout: 10
      validation-timeout: 5000
      initialization-fail-timeout: 1000
      connection-test-query: SELECT 1
    #dbcp2:
      #initial-size: 5
      #min-idle: 5
      #max-active: 20
      #test-on-borrow: true
      #waiting times /ms
      #max-wait: 60000
      

