server:
  port: 1112
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fast-product
        uri: lb://fast-product
        predicates:
        - Path=/fast-product/**
        filters:
        - StripPrefix=1
        #- Auth
        #- RewritePath=/employee/(?<path>.*), /$\{path}
      - id: fast-sysManager
        uri: lb://fast-sysManager
        predicates:
        - Path=/fast-sysManager/**
        filters:
        - StripPrefix=1
      - id: fast-fast-autoCode
        uri: lb://fast-autoCode
        predicates:
        - Path=/fast-sysManager/**
        filters:
        - StripPrefix=1
      - id: fast-auth
        uri: lb://fast-auth
        predicates:
        - Path=/fast-auth/**
        filters:
        - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
