
# ===================================================================
# framework specific properties
# ===================================================================

# datasource
spring:
  datasource:
    druid:
      driver-calss-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://183.6.111.117:50009/cloud-vue?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: fast
      password: Fast123_
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      #waiting times /ms
      max-wait: 60000
      

