# spring session
spring:
  session: stateless
  #mvc: /file/**
  resources: 
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./fileRoot/
  
#ribbon
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
  # 失败重试 false只对get重试，true全部重试
  OkToRetryOnAllOperations: false

#允许服务降级
feign:
  hystrix:
    enabled: true

#management

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
        
#        exclude: env,beans
#        include: health,info,refresh

# log4j2
#logging:
  #config: ${spring.cloud.config.uri}/fast-logging-${spring.profiles.active}.yml
