# ===================================================================
# framework specific properties
# ===================================================================

# datasource
druid:
  url: jdbc:mysql://localhost:3306/cloud-vue?useUnicode=true&characterEncoding=utf8&useSSL=false
  driver-class: com.mysql.jdbc.Driver
  username: root
  password: root
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
