spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fast-product
        uri: lb://fast-product
        predicates:
        - Path=/test/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
  
