spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: fast-product
        uri: lb://fast-product
        predicates:
        - Path=/fast-product/**
        filters:
        - StripPrefix=1
        #- RewritePath=/employee/(?<path>.*), /$\{path}
  
